import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { git } from "./git.ts";
import { ghostqDir, samePath, templateDir } from "./paths.ts";

const PREV_STATE_FILE = "prev-templatedir";
// distinctive line in our shim; lets a re-install tell its own post-checkout
// apart from a foreign one carried by the seed
const SHIM_MARKER = "generated by `ghostq install`";

function shellQuote(s: string): string {
  return `'${s.replaceAll("'", "'\\''")}'`;
}

async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(
    () => true,
    () => false,
  );
}

// Undo a legacy core.hooksPath-based install (ghostq before it moved to
// init.templateDir). That global core.hooksPath makes git look ONLY there,
// shadowing .git/hooks — so leaving it set would keep overriding the new
// template hook and silently preserve the old coexistence bug for upgraders.
// Restore the core.hooksPath ghostq had recorded, then drop the stale dir.
async function migrateLegacyHooksPath(): Promise<boolean> {
  const legacyHooks = join(ghostqDir(), "hooks");
  const chp = git(["config", "--global", "--get", "core.hooksPath"]);
  if (chp.status !== 0 || !samePath(chp.stdout, legacyHooks)) return false;

  const legacyPrev = (
    await fs.readFile(join(legacyHooks, "prev-hookspath"), "utf8").catch(() => "")
  ).trim();
  if (legacyPrev !== "") git(["config", "--global", "core.hooksPath", legacyPrev]);
  else git(["config", "--global", "--unset", "core.hooksPath"]);
  await fs.rm(legacyHooks, { recursive: true, force: true });
  return true;
}

// ghostq hooks via init.templateDir, NOT core.hooksPath. Why-not core.hooksPath:
// git honours only one hooks directory, so a global core.hooksPath shadows every
// repo-local .git/hooks and forces ghostq to multiplex every hook AND trips the
// guards in lefthook/husky (they refuse to install while it is set). templateDir
// instead seeds .git/hooks on clone/init and then steps out of the way — git
// uses the repo's own .git/hooks, so any hook manager coexists untouched.
//
// The one thing templateDir cannot cover: `git worktree add` runs the single
// shared .git/hooks/post-checkout, so a tool whose config also owns
// post-checkout displaces ghostq there (its clone was still linked; only later
// worktrees in that repo need a manual `ghostq apply`). Two tools cannot both
// own one hook slot — that is a git limitation, not one ghostq can design away.
function postCheckoutShim(binPath: string, chainOrig: boolean): string {
  const chain = chainOrig
    ? `
# chain to a post-checkout this template already carried
GHOSTQ_ORIG="$(dirname "$0")/post-checkout.ghostq-orig"
if [ -x "$GHOSTQ_ORIG" ]; then
  "$GHOSTQ_ORIG" "$@"
fi
`
    : "";
  return `#!/bin/sh
# post-checkout hook ${SHIM_MARKER} via git's init.templateDir.
# Re-run \`ghostq install\` to regenerate, \`ghostq uninstall\` to remove.
#
# Copied into .git/hooks on every clone / \`git init\`, so a fresh checkout links
# your overlay files. ghostq never sets core.hooksPath, leaving the hooks path
# free for lefthook, husky, pre-commit, and friends.
${chain}
# Fast path: only a fresh clone or \`git worktree add\` reports the null ref
# as the previous HEAD together with the branch flag. Every ordinary
# checkout/switch exits here without spawning ghostq.
[ "$3" = "1" ] || exit 0
case "\${1:-}" in
  "") exit 0 ;;
  *[!0]*) exit 0 ;;
esac

GHOSTQ_BIN=${shellQuote(binPath)}
if [ -x "$GHOSTQ_BIN" ]; then
  "$GHOSTQ_BIN" apply
elif command -v ghostq >/dev/null 2>&1; then
  ghostq apply
fi
exit 0
`;
}

// process.execPath alone is not enough: when running from source it is the
// bun runtime, not ghostq, so the shim gets a wrapper that re-invokes bun with
// the entry script. The wrapper lives outside the template dir so it is not
// copied into every clone.
async function resolveBinPath(): Promise<string> {
  const script = process.argv[1] ?? "";
  const compiled = script.startsWith("/$bunfs/") || !/\.(ts|js|mjs)$/.test(script);
  if (compiled) return process.execPath;

  const wrapper = join(ghostqDir(), "ghostq-dev");
  await fs.writeFile(
    wrapper,
    `#!/bin/sh\nexec ${shellQuote(process.execPath)} ${shellQuote(resolve(script))} "$@"\n`,
    { mode: 0o755 },
  );
  return wrapper;
}

// Reproduce the template a normal clone would otherwise get — git's built-in
// default, or the user's own init.templateDir if they had one — so overriding
// init.templateDir does not silently drop .git/info/exclude, description, and
// the sample hooks. A throwaway `git init` materializes the currently-effective
// template portably, with no hard-coded system paths.
async function seedTemplate(dst: string): Promise<void> {
  const tmp = await fs.mkdtemp(join(tmpdir(), "ghostq-seed-"));
  try {
    const repo = join(tmp, "r");
    const r = git(["init", "-q", repo]);
    if (r.status !== 0) return;
    const gitDir = join(repo, ".git");
    for (const name of ["hooks", "info", "branches", "description"]) {
      await fs.cp(join(gitDir, name), join(dst, name), { recursive: true }).catch(() => {});
    }
  } finally {
    await fs.rm(tmp, { recursive: true, force: true });
  }
}

export async function install(): Promise<number> {
  const dir = templateDir();
  const hooks = join(dir, "hooks");
  const stateFile = join(ghostqDir(), PREV_STATE_FILE);

  if (await migrateLegacyHooksPath()) {
    console.log("migrated off the legacy core.hooksPath install");
  }

  const current = git(["config", "--global", "--get", "init.templateDir"]);
  let prev = "";
  if (current.status === 0 && current.stdout !== "" && !samePath(current.stdout, dir)) {
    prev = current.stdout;
  } else {
    // on re-install init.templateDir already points at us; recording that
    // would lose the original value uninstall needs to restore
    prev = (await fs.readFile(stateFile, "utf8").catch(() => "")).trim();
  }

  await fs.mkdir(hooks, { recursive: true });
  await seedTemplate(dir);
  await fs.writeFile(stateFile, prev === "" ? "" : `${prev}\n`);

  // preserve a foreign post-checkout the seed carried (a prior install's own
  // shim, identified by the marker, is simply overwritten)
  const shimPath = join(hooks, "post-checkout");
  const origPath = join(hooks, "post-checkout.ghostq-orig");
  if (await exists(shimPath)) {
    const body = await fs.readFile(shimPath, "utf8").catch(() => "");
    if (!body.includes(SHIM_MARKER)) await fs.rename(shimPath, origPath);
  }
  const chainOrig = await exists(origPath);

  const binPath = await resolveBinPath();
  await fs.writeFile(shimPath, postCheckoutShim(binPath, chainOrig), { mode: 0o755 });

  const set = git(["config", "--global", "init.templateDir", dir]);
  if (set.status !== 0) {
    console.error(`ghostq: failed to set init.templateDir: ${set.stderr}`);
    return 1;
  }

  console.log(`installed post-checkout template: ${shimPath}`);
  console.log(`set global init.templateDir: ${dir}`);
  if (prev !== "") console.log(`preserved previous templateDir: ${prev}`);
  console.log("new clones and worktrees link automatically; run `ghostq apply` once in repos cloned before this");
  return 0;
}

export async function uninstall(): Promise<number> {
  const dir = templateDir();
  const stateFile = join(ghostqDir(), PREV_STATE_FILE);
  const prev = (await fs.readFile(stateFile, "utf8").catch(() => "")).trim();

  const current = git(["config", "--global", "--get", "init.templateDir"]);
  if (current.status === 0 && current.stdout !== "" && samePath(current.stdout, dir)) {
    if (prev !== "") {
      git(["config", "--global", "init.templateDir", prev]);
      console.log(`restored global init.templateDir: ${prev}`);
    } else {
      git(["config", "--global", "--unset", "init.templateDir"]);
      console.log("unset global init.templateDir");
    }
  } else {
    console.log("global init.templateDir is not managed by ghostq; leaving it as is");
  }

  if (await migrateLegacyHooksPath()) {
    console.log("also removed the legacy core.hooksPath install");
  }

  await fs.rm(dir, { recursive: true, force: true });
  await fs.rm(stateFile, { force: true });
  await fs.rm(join(ghostqDir(), "ghostq-dev"), { force: true });
  console.log(`removed ${dir}`);
  return 0;
}
