import { promises as fs } from "node:fs";
import { join, resolve } from "node:path";
import { git } from "./git.ts";
import { hooksDir, samePath } from "./paths.ts";

const PREV_STATE_FILE = "prev-hookspath";

function shellQuote(s: string): string {
  return `'${s.replaceAll("'", "'\\''")}'`;
}

function shimSource(prevHooksPath: string, binPath: string): string {
  return `#!/bin/sh
# post-checkout dispatcher generated by \`ghostq install\`.
# Re-run \`ghostq install\` to regenerate, \`ghostq uninstall\` to remove.

# When core.hooksPath is set, git looks ONLY here — so this dispatcher must
# chain to the hooks it shadows before doing its own work.

# 1) the global core.hooksPath that was configured before ghostq install
GHOSTQ_PREV_HOOKS=${shellQuote(prevHooksPath)}
if [ -n "$GHOSTQ_PREV_HOOKS" ] && [ -x "$GHOSTQ_PREV_HOOKS/post-checkout" ]; then
  "$GHOSTQ_PREV_HOOKS/post-checkout" "$@"
fi

# 2) repo-local hooks (lefthook, plain .git/hooks, ...)
GHOSTQ_COMMON_DIR=$(git rev-parse --git-common-dir 2>/dev/null)
if [ -n "$GHOSTQ_COMMON_DIR" ] && [ -x "$GHOSTQ_COMMON_DIR/hooks/post-checkout" ]; then
  "$GHOSTQ_COMMON_DIR/hooks/post-checkout" "$@"
fi

# Fast path: only a fresh clone or \`git worktree add\` reports the null ref
# as the previous HEAD together with the branch flag. Every ordinary
# checkout/switch exits here without spawning ghostq.
[ "$3" = "1" ] || exit 0
case "\${1:-}" in
  "") exit 0 ;;
  *[!0]*) exit 0 ;;
esac

GHOSTQ_BIN=${shellQuote(binPath)}
if [ -x "$GHOSTQ_BIN" ]; then
  "$GHOSTQ_BIN" apply
elif command -v ghostq >/dev/null 2>&1; then
  ghostq apply
fi
exit 0
`;
}

// process.execPath alone is not enough: when running from source it is the
// bun runtime, not ghostq, so the shim gets a wrapper that re-invokes bun
// with the entry script.
async function resolveBinPath(dir: string): Promise<string> {
  const script = process.argv[1] ?? "";
  const compiled = script.startsWith("/$bunfs/") || !/\.(ts|js|mjs)$/.test(script);
  if (compiled) return process.execPath;

  const wrapper = join(dir, "ghostq-dev");
  await fs.writeFile(
    wrapper,
    `#!/bin/sh\nexec ${shellQuote(process.execPath)} ${shellQuote(resolve(script))} "$@"\n`,
    { mode: 0o755 },
  );
  return wrapper;
}

export async function install(): Promise<number> {
  const dir = hooksDir();
  await fs.mkdir(dir, { recursive: true });
  const stateFile = join(dir, PREV_STATE_FILE);

  const current = git(["config", "--global", "--get", "core.hooksPath"]);
  let prev = "";
  if (current.status === 0 && current.stdout !== "" && !samePath(current.stdout, dir)) {
    prev = current.stdout;
  } else {
    // on re-install core.hooksPath already points at us; recording that
    // would lose the original value uninstall needs to restore
    prev = (await fs.readFile(stateFile, "utf8").catch(() => "")).trim();
  }
  await fs.writeFile(stateFile, prev === "" ? "" : `${prev}\n`);

  const binPath = await resolveBinPath(dir);
  await fs.writeFile(join(dir, "post-checkout"), shimSource(prev, binPath), { mode: 0o755 });

  const set = git(["config", "--global", "core.hooksPath", dir]);
  if (set.status !== 0) {
    console.error(`ghostq: failed to set core.hooksPath: ${set.stderr}`);
    return 1;
  }

  console.log(`installed post-checkout hook: ${join(dir, "post-checkout")}`);
  console.log(`set global core.hooksPath: ${dir}`);
  if (prev !== "") console.log(`chaining to previous hooksPath: ${prev}`);
  return 0;
}

export async function uninstall(): Promise<number> {
  const dir = hooksDir();
  const stateFile = join(dir, PREV_STATE_FILE);
  const prev = (await fs.readFile(stateFile, "utf8").catch(() => "")).trim();

  const current = git(["config", "--global", "--get", "core.hooksPath"]);
  if (current.status === 0 && current.stdout !== "" && samePath(current.stdout, dir)) {
    if (prev !== "") {
      git(["config", "--global", "core.hooksPath", prev]);
      console.log(`restored global core.hooksPath: ${prev}`);
    } else {
      git(["config", "--global", "--unset", "core.hooksPath"]);
      console.log("unset global core.hooksPath");
    }
  } else {
    console.log("global core.hooksPath is not managed by ghostq; leaving it as is");
  }

  await fs.rm(dir, { recursive: true, force: true });
  console.log(`removed ${dir}`);
  return 0;
}
